import config
from util import click_element, hide_overlay, show_overlay, show_page, show_page_typewriter, wait

class PheasaKhmer:
    def select_and_run_example(self, example, text):
        show_overlay(text, 5, False)
        click_element(f"//div[@id='{example}']//button")
        wait(5)
        hide_overlay()

    def rundemo(self, url):
        config.driver.get(url)
        wait(1)
        click_element("//label[@for='btn-language-english']", False)
        wait(1)
        click_element("//button[@id='help-ok']", False)
        wait(1)
        show_page_typewriter('Das Alphabet von Khmer hat 74 Buchstaben. Manche Vokale werden vor den Konsonanten geschrieben, aber danach gesprochen. Die Frage ist nun, wie schreibt man das am Computer: so wie es da steht (erst Vokal, dann Konsonant) oder so wie es gesprochen wird (erst Konsonant, dann Vokal)?', False)
        show_page_typewriter('Bei der Anzeige macht es keinen Unterschied, aber es wird unterschiedlich gespeichert. Deshalb zeigen z.B. Suchen unterschiedliche Ergebnisse.', False)
        show_page_typewriter('Schauen wir uns das mal näher an: Das Wort ខ្មែរ („Khmer“) kann auf zwei Arten geschrieben werden:', True)
        wait(1)
        click_element("//button[@id='btn-examples']")
        click_element("//div[@id='dropdown-examples']/ul/li/button[@data-examples='#example0']")
        self.select_and_run_example('example-1', 'richtige Reihenfolge')
        self.select_and_run_example('example-2', 'falsche Reihenfolge')
        click_element("//button[@id='btn-examples']")
        click_element("//div[@id='dropdown-examples']/ul/li/button[@data-examples='#example1']")
        show_page('Bei anderen Wörtern gibt es viel mehr Möglichkeiten, wie z.B. ស្ត្រី („stri“, Frau). Was ist da die richtige Schreibweise?', True, 5)
        self.select_and_run_example('example-2', 'So?')
        show_overlay('So? - Nein.', 2, True)
        self.select_and_run_example('example-4', 'Oder so?')
        show_overlay('Oder so? - Nein.', 2, True)
        self.select_and_run_example('example-3', 'Oder vielleicht so?')
        self.select_and_run_example('example-1', 'So?')
        show_overlay('So? - Ja!', 2, True)
        show_page('<p>Das mit <b>Keyman</b> erstellte Tastaturlayout enthält Regeln, die die Zeichen in die richtige Reihenfolge bringen, so dass es keine Rolle spielt, in welcher Reihenfolge die Tasten gedrückt werden.</p><p>Endlich richtig gut schreiben können:<br> <b>Wie gut, dass es Keyman gibt.</b></p>', True, 15)
        show_page('<p>Fassen wir zusammen: Mit der von SIL entwickelten <b>Keyman-Software</b> können Tastaturbelegungen für beliebige Sprachen entwickelt und benutzt werden.</p><p>Keyman macht es möglich, dass Menschen aus den eher unbeachteten und oft unterdrückten Volksgruppen ihre Sprache auf dem Computer oder auf dem Smartphone schreiben können &ndash; eine notwendige Voraussetzung für Bildungsprojekte und Bibelübersetzung.</p>', True, 15)
        show_page('<p><b>Keyman</b> ist ein Produkt von <i>SIL Language Technology</i>. SIL ist die wichtigste Partnerorganisation von Wycliff. Die Mitarbeiter der Abteilung <i>SIL Language Technology</i> entwickeln seit über 40 Jahren spezielle Software für Bibelübersetzungs-, Bildungs- und Sprachprojekte.</p><p>www.keyman.com</p>', True, 15)
        show_page('<p>In den Software-Entwicklungs-Teams bei <i>SIL Language Technology</i> arbeiten Ehrenamtliche, vollzeitliche Wycliff-Missionare (mit persönlichem Unterstützerkreis), Studierende und (aus Projektgeldern bezahlte) angestellte Mitarbeiter zusammen. Die meisten arbeiten „remote“, also von ihren Heimatländern aus.</p>', True, 10)
        show_page('<p><span style="color:red">Geben</span> • <span style="color:red">Beten</span> • <span style="color:red">Mitarbeiten</span></p><p>Die Software-Projekte von SIL Language Technology brauchen dein Engagement!</p>', True, 10)
        show_page('<p>Software-Entwicklung ist dein Ding? Hast du Erfahrung im Projekt-Management, Testen von Software oder Webdesign?</p><p>Dann könntest du einen entscheidenden Beitrag zur Weiterentwicklung von Software für Bibelübersetzungs-, Bildungs- und Sprachprojekte leisten.</p>', True, 15)
        show_page('<p>Danke für dein Mitdenken, fürs Überlegen, ob du mitarbeiten kannst, deine Spende(n) und deine Fürbitte fürs Keyman-Projekt!</p><p>www.keyman.com</p>', True, 15)
